<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Foody Restaurant</title>
    <link href="plugin/bootstrap/bootstrap.css" rel="stylesheet">
   <!--<link href="plugin/bootstrap/datepicker.css" rel="stylesheet">--> 


    <link href="plugin/font-awesome/font-awesome.css" rel="stylesheet">
    <!--teb3a les icon mta3 socila media-->

    <link href="plugin/revolution-plugin/settings.css" rel="stylesheet">
    <!--teb3a WE’RE FOODY Restaurant-->


    <link href="plugin/owl-carousel/owl.theme.default.css" rel="stylesheet">
    <!--teb3a About Us-->

    <link href="plugin/owl-carousel/owl.carousel.css" rel="stylesheet">
    <!--teb3a Our Awesome Chef-->

    <link href="plugin/slick-slider/slick-theme.css" rel="stylesheet">
    <!--teb3a Previous & next mta3 Our Food-->


    <link href="plugin/animation/animate.min.css" rel="stylesheet">
    <!--teb3a les icon mta3 kol section-->

    <link href="css/theme.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">

</head>

<body>
    <!-- Page pre loader -->
    <div id="pre-loader">
        <div class="loader-holder">
            <div class="frame">
                <img src="images/Preloader.gif" alt="Laboom" />
            </div>
        </div>
    </div>
    <div class="wrapper">
        <!--  a Header -->
        <header>
            <div class="header-part header-reduce sticky">
                <div class="header-top">
                    <div class="container">
                        <div class="header-top-inner">
                            <div class="header-top-left">
                                <a href="#" class="top-cell"><img src="images/fon.png" alt=""> <span>23-349-082</span></a>
                                <a href="#" class="top-email"><span>support@foody.com</span></a>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="header-bottom">
                    <div class="container">
                        <div class="header-info">
                            <div class="header-info-inner">
                                <div class="book-table header-collect book-md">
                                    <a href="#" data-toggle="modal" data-target="#login"><img src="images/login.png" alt="">Login</a>
                                </div>

                                <div class="search-part">
                                    <a href="#"></a>
                                    <div class="search-box">
                                        <input type="text" name="txt" placeholder="Search">
                                        <input type="submit" name="submit" value=" ">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="menu-icon">
                            <a href="#" class="hambarger">
                                <span class="bar-1"></span>
                                <span class="bar-2"></span>
                                <span class="bar-3"></span>
                            </a>
                        </div>


                        <div class="book-table header-collect book-sm">
                            <a href="#" data-toggle="modal" data-target="#login"><img src="images/login.png" alt="">Login</a>
                        </div>
                        <div class="menu-main">
                            <ul>
                                <li class="mega-menu">
                                    <a href="<?= $_SERVER["PHP_SELF"]; ?>">Home</a>
                                </li>

                                <li class="mega-menu">
                                    <a href="#menu">Menu</a>
                                    
                                </li>
                                <li class="mega-menu">
                                    <a href="#ourfood">Our Food</a>
                                </li>


                                <li class="mega-menu">
                                    <a href="#about_us">About Us</a>

                                </li>

                                <li class="mega-menu">
                                    <a href="#contact">Contact</a>
                                </li>
                            </ul>
                        </div>
                        <div class="logo">
                            <a href="<?= $_SERVER["PHP_SELF"]; ?>"><img src="images/logo.png" alt=""></a>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- End Header -->
        <!-- Start Main -->
        <main>
            <div class="main-part">
                <!-- Start Slider Part -->
                <section class="home-slider">
                    <div class="tp-banner-container">
                        <div class="tp-banner">
                            <ul>
                                <li data-transition="zoomout" data-slotamount="2" data-masterspeed="1000" data-thumb="" data-saveperformance="on" data-title="Slide">
                                    <img src="images/dummy.png" alt="slidebg1" data-lazyload="images/slider1.jpg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                                    <!-- LAYERS -->
                                    <div class="tp-caption very_large_text" data-x="center" data-hoffset="0" data-y="250" data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;" data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                                        data-speed="1000" data-start="500" data-easing="Back.easeInOut" data-endspeed="300">WE’RE <span>FOODY</span> <i>Restaurant</i>
                                    </div>
                                    <!-- LAYERS -->
                                    <div class="tp-caption medium_text" data-x="center" data-hoffset="0" data-y="340" data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;" data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                                        data-speed="1000" data-start="500" data-easing="Back.easeInOut" data-endspeed="300">Delicacies Food & Drinks
                                    </div>
                                    <!-- LAYERS -->
                                    <div class="tp-caption" data-x="center" data-hoffset="0" data-y="425" data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;" data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                                        data-speed="1000" data-start="500" data-easing="Back.easeInOut" data-endspeed="300"><a href="#" class="button-white" data-toggle="modal" data-target="#login">Explore NOW</a>
                                    </div>
                                </li>
                                <li data-transition="zoomout" data-slotamount="2" data-masterspeed="1000" data-thumb="" data-saveperformance="on" data-title="Slide">
                                    <img src="images/dummy.png" alt="slidebg1" data-lazyload="images/slider1.jpg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                                    <!-- LAYERS -->
                                    <div class="tp-caption very_large_text" data-x="center" data-hoffset="0" data-y="250" data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;" data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                                        data-speed="1000" data-start="500" data-easing="Back.easeInOut" data-endspeed="300">WE’RE <span>FOODY</span> <i>Restaurant</i>
                                    </div>
                                    <!-- LAYERS -->
                                    <div class="tp-caption medium_text" data-x="center" data-hoffset="0" data-y="340" data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;" data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                                        data-speed="1000" data-start="500" data-easing="Back.easeInOut" data-endspeed="300">Delicacies Food & Drinks
                                    </div>
                                    <!-- LAYERS -->
                                    <div class="tp-caption" data-x="center" data-hoffset="0" data-y="425" data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;" data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                                        data-speed="1000" data-start="500" data-easing="Back.easeInOut" data-endspeed="300"><a href="#" class="button-white" data-toggle="modal" data-target="#login">Explore NOW</a>
                                    </div>
                                </li>
                                <li data-transition="zoomout" data-slotamount="2" data-masterspeed="1000" data-thumb="" data-saveperformance="on" data-title="Slide">
                                    <img src="images/dummy.png" alt="slidebg1" data-lazyload="images/slider1.jpg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                                    <!-- LAYERS -->
                                    <div class="tp-caption very_large_text" data-x="center" data-hoffset="0" data-y="250" data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;" data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                                        data-speed="1000" data-start="500" data-easing="Back.easeInOut" data-endspeed="300">WE’RE <span>LABOOM</span> <i>Restaurant</i>
                                    </div>
                                    <!-- LAYERS -->
                                    <div class="tp-caption medium_text" data-x="center" data-hoffset="0" data-y="340" data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;" data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                                        data-speed="1000" data-start="500" data-easing="Back.easeInOut" data-endspeed="300">Delicacies Food & Drinks
                                    </div>
                                    <!-- LAYERS -->
                                    <div class="tp-caption" data-x="center" data-hoffset="0" data-y="425" data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;" data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                                        data-speed="1000" data-start="500" data-easing="Back.easeInOut" data-endspeed="300"><a href="#" class="button-white">Explore NOW</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </section>
                <!-- End Slider Part -->
                <!-- Start Welcome Part -->
                <section id="reach-to" class="welcome-part home-icon">
                    <div class="icon-default">
                        <a href="#reach-to" class="scroll"><img src="images/scroll-arrow.png" alt=""></a>
                    </div>
                    <div class="container">
                        <div class="build-title">
                            <h2>Welcome To Foody</h2>
                            <h6>it's our way of living.</h6>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-12 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                                <p>Foody,a Mediterranean restaurant in Bizerte ,Tunisia (about an hour from the capital) is the world’s best, according to the 2019 list of The World’s 50 Best Restaurants, which ranks based on the votes of 1,000 international
                                    industry experts.</p>
                                <p><img src="images/signature.png" alt=""></p>

                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                                <img src="images/img2.png" alt="">
                            </div>
                        </div>
                    </div>
                    <div class="float-main">
                        <div class="icon-top-left">
                            <img src="images/icon1.png" alt="">
                        </div>
                        <div class="icon-bottom-left">
                            <img src="images/icon2.png" alt="">
                        </div>
                        <div class="icon-top-right">
                            <img src="images/icon3.png" alt="">
                        </div>
                        <div class="icon-bottom-right">
                            <img src="images/icon4.png" alt="">
                        </div>
                    </div>
                </section>
                <!-- End Welcome Part -->
                <!-- Start Dishes Part -->
                <section class="dishes banner-bg invert invert-black home-icon wow fadeInDown" data-background="images/banner1.jpg" data-wow-duration="1000ms" data-wow-delay="300ms" id="ourfood">
                    <div class="icon-default icon-black">
                        <img src="images/icon5.png" alt="">
                    </div>
                    <div class="container">
                        <div class="build-title">
                            <h2>Our Food</h2>
                            <h6>it's our way of living.</h6>
                        </div>
                        <div class="slider multiple-items">
                            <div class="product-blog">
                                <img src="images/product1.png" alt="">
                                <h3>Quattro Formaggi</h3>
                                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames</p>
                                <del>$ 55.00</del><strong class="txt-default">$ 18.00</strong>
                            </div>
                            <div class="product-blog">
                                <img src="images/product2.png" alt="">
                                <h3>Vegetarian Pasta</h3>
                                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames</p>
                                <del>$ 55.00</del><strong class="txt-default">$ 18.00</strong>
                            </div>
                            <div class="product-blog">
                                <img src="images/product3.png" alt="">
                                <h3>Gluten-Free Pasta</h3>
                                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames</p>
                                <del>$ 55.00</del><strong class="txt-default">$ 18.00</strong>
                            </div>
                            <div class="product-blog">
                                <img src="images/product1.png" alt="">
                                <h3>Quattro Formaggi</h3>
                                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames</p>
                                <del>$ 55.00</del><strong class="txt-default">$ 18.00</strong>
                            </div>
                            <div class="product-blog">
                                <img src="images/product2.png" alt="">
                                <h3>Vegetarian Pasta</h3>
                                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames</p>
                                <del>$ 55.00</del><strong class="txt-default">$ 18.00</strong>
                            </div>
                            <div class="product-blog">
                                <img src="images/product3.png" alt="">
                                <h3>Gluten-Free Pasta</h3>
                                <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames</p>
                                <del>$ 55.00</del><strong class="txt-default">$ 18.00</strong>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- End Dishes Part -->
                <!-- Start Menu Part -->
                <section class="special-menu bg-skeen home-icon wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms" id="menu">
                    <div class="icon-default icon-skeen">
                        <img src="images/icon6.png" alt="">
                    </div>
                    <div class="container">
                        <div class="build-title">
                            <h2>Our Special Menu </h2>
                            <h6>The role of a good cook ware in the preparation of a sumptuous meal cannot be over emphasized then one consider white bread</h6>
                        </div>
                        <div class="menu-wrapper">
                            <div class="portfolioFilter">
                                <div class="portfolioFilter-inner">
                                    <a href="javascript:;" data-filter="*" class="current">All</a>
                                    <a href="javascript:;" data-filter=".breakfast">BREAKFAST</a>
                                    <a href="javascript:;" data-filter=".dessert">DESSERT</a>
                                    <a href="javascript:;" data-filter=".dinner">DINNER</a>
                                    <a href="javascript:;" data-filter=".freshfood">FRESHFOOD</a>
                                    <a href="javascript:;" data-filter=".lunch">LUNCH</a>
                                </div>
                            </div>
                            <div class="portfolioContainer row">
                                <?php
                                        while($row = $productList->fetch()){ 
                                            echo "<div class='col-md-6 col-sm-6 col-xs-12 isotope-item ".$row["categorie"]."'>
                                                        <div class='menu-list'>
                                                            <span class='menu-list-product'>";
                                                                echo '<img src="img/'.$row['file'].'" alt="">';
                                                        echo" </span>
                                                        <h5>".$row["name"]."<span>$ ". $row["price"]."</span></h5>
                                                        <p>".$row["description"]."</p>
                                                </div></div>";
                                        }
                                ?>
                            </div>
                            <div class="btn-outer">
                                <a href="#" class="btn-main btn-shadow">Explore Full Menu</a>
                            </div>
                        </div>
                    </div>
                    <div class="float-main">
                        <div class="icon-top-left">
                            <img src="images/icon7.png" alt="">
                        </div>
                        <div class="icon-bottom-left">
                            <img src="images/icon8.png" alt="">
                        </div>
                        <div class="icon-top-right">
                            <img src="images/icon9.png" alt="">
                        </div>
                        <div class="icon-bottom-right">
                            <img src="images/icon10.png" alt="">
                        </div>
                    </div>
                </section>
                <!-- End Menu Part -->
                <!-- Start Chef -->
                <section class="chef-part home-icon wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms" id="our_chef">
                    <div class="icon-default">
                        <img src="images/icon11.png" alt="">
                    </div>
                    <div class="container">
                        <div class="build-title">
                            <h2>Our Awesome Chef</h2>
                            <h6>Meet Professional Cook Team</h6>
                        </div>
                        <div class="owl-carousel owl-theme chef-slider" data-items="4" data-laptop="3" data-tablet="2" data-mobile="1" data-nav="true" data-dots="false" data-autoplay="true" data-speed="1800" data-autotime="5000">
                            <div class="item">
                                <div class="chef-blog">
                                    <div class="chef-inner">
                                        <div class="chef-member">
                                            <img src="images/chef1.png" alt="">
                                        </div>
                                        <div class="chef-info">
                                            <h5>Anna Taylor</h5>
                                            <span>Head Chief</span>
                                            <div class="social-top">
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="chef-blog">
                                    <div class="chef-inner">
                                        <div class="chef-member">
                                            <img src="images/chef2.png" alt="">
                                        </div>
                                        <div class="chef-info">
                                            <h5>Alex Wilson</h5>
                                            <span>Head Chief</span>
                                            <div class="social-top">
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="chef-blog">
                                    <div class="chef-inner">
                                        <div class="chef-member">
                                            <img src="images/chef3.png" alt="">
                                        </div>
                                        <div class="chef-info">
                                            <h5>Anita Golden</h5>
                                            <span>Head Chief</span>
                                            <div class="social-top">
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="chef-blog">
                                    <div class="chef-inner">
                                        <div class="chef-member">
                                            <img src="images/chef4.png" alt="">
                                        </div>
                                        <div class="chef-info">
                                            <h5>Benderd Dimitor</h5>
                                            <span>Head Chief</span>
                                            <div class="social-top">
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="chef-blog">
                                    <div class="chef-inner">
                                        <div class="chef-member">
                                            <img src="images/chef1.png" alt="">
                                        </div>
                                        <div class="chef-info">
                                            <h5>Anna Taylor</h5>
                                            <span>Head Chief</span>
                                            <div class="social-top">
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="chef-blog">
                                    <div class="chef-inner">
                                        <div class="chef-member">
                                            <img src="images/chef2.png" alt="">
                                        </div>
                                        <div class="chef-info">
                                            <h5>Alex Wilson</h5>
                                            <span>Head Chief</span>
                                            <div class="social-top">
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="chef-blog">
                                    <div class="chef-inner">
                                        <div class="chef-member">
                                            <img src="images/chef3.png" alt="">
                                        </div>
                                        <div class="chef-info">
                                            <h5>Anita Golden</h5>
                                            <span>Head Chief</span>
                                            <div class="social-top">
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="chef-blog">
                                    <div class="chef-inner">
                                        <div class="chef-member">
                                            <img src="images/chef4.png" alt="">
                                        </div>
                                        <div class="chef-info">
                                            <h5>Benderd Dimitor</h5>
                                            <span>Head Chief</span>
                                            <div class="social-top">
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="float-main">
                        <div class="icon-top-left">
                            <img src="images/icon12.png" alt="">
                        </div>
                        <div class="icon-bottom-left">
                            <img src="images/icon13.png" alt="">
                        </div>
                        <div class="icon-top-right">
                            <img src="images/icon14.png" alt="">
                        </div>
                    </div>
                </section>
                <!-- End Chef -->
                <!-- Start Food Hours -->
                <section class="food-hours home-icon wow fadeInDown" data-stellar-offset-parent="true" data-stellar-background-ratio="0.5" data-wow-duration="1000ms" data-wow-delay="300ms" style="background-image: url('images/banner2.jpg');">
                    <div class="icon-default icon-gold">
                        <img src="images/icon19.png" alt="">
                    </div>
                    <div class="container">
                        <div class="food-blog">
                            <div class="row">
                                <div class="col-md-3 col-sm-3 col-xs-12 food-mxs">
                                    <div class="food-blog-inner">
                                        <div class="food-item">
                                            <div class="food-item-inner">
                                                <img src="images/icon15.png" alt="">
                                            </div>
                                        </div>
                                        <h2>Breakfast</h2>
                                        <span>8.00 am 10.00 am</span>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-3 col-xs-12 food-mxs">
                                    <div class="food-blog-inner">
                                        <div class="food-item">
                                            <div class="food-item-inner">
                                                <img src="images/icon16.png" alt="">
                                            </div>
                                        </div>
                                        <h2>Lunch</h2>
                                        <span>1.00 am 2.00 am</span>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-3 col-xs-12 food-mxs">
                                    <div class="food-blog-inner">
                                        <div class="food-item">
                                            <div class="food-item-inner">
                                                <img src="images/icon17.png" alt="">
                                            </div>
                                        </div>
                                        <h2>Dinner</h2>
                                        <span>7.00 am 9.00 am</span>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-3 col-xs-12 food-mxs">
                                    <div class="food-blog-inner">
                                        <div class="food-item">
                                            <div class="food-item-inner">
                                                <img src="images/icon18.png" alt="">
                                            </div>
                                        </div>
                                        <h2>Dessert</h2>
                                        <span>All Day</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- End Food Hours -->
                <!-- Start Feature Blog -->
                <section class="bg-skeen feature-list text-center home-icon wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms" id="our_Feature">
                    <div class="icon-default icon-skeen">
                        <img src="images/icon22.png" alt="">
                    </div>
                    <div class="container">
                        <div class="build-title">
                            <h2>Our Some Feature</h2>
                            <h6>The role of a good cook ware in the preparation of a sumptuous meal cannot be <br> over emphasized then one consider white bread</h6>
                        </div>
                        <div class="row">
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="feature-list-icon">
                                    <div class="feature-icon-table">
                                        <img src="images/img9.png" alt="">
                                    </div>
                                </div>
                                <h5>Fresh Dishes</h5>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius-</p>
                            </div>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="feature-list-icon">
                                    <div class="feature-icon-table">
                                        <img src="images/img10.png" alt="">
                                    </div>
                                </div>
                                <h5>Various Menu</h5>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius-</p>
                            </div>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="feature-list-icon">
                                    <div class="feature-icon-table">
                                        <img src="images/img11.png" alt="">
                                    </div>
                                </div>
                                <h5>Well Service</h5>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius-</p>
                            </div>
                            <div class="col-md-3 col-sm-6 col-xs-12">
                                <div class="feature-list-icon">
                                    <div class="feature-icon-table">
                                        <img src="images/img12.png" alt="">
                                    </div>
                                </div>
                                <h5>Fast Delivery</h5>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius-</p>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- End Feature Blog -->
                <!-- Start Client Say -->
                <section class="client banner-bg invert invert-black home-icon wow fadeInDown" data-background="images/banner3.jpg" data-wow-duration="1000ms" data-wow-delay="300ms" id="about_us">
                    <div class="icon-default icon-black">
                        <img src="images/icon21.png" alt="">
                    </div>
                    <div class="container">
                        <div class="build-title">
                            <h2>About Us</h2>
                            <h6>Team Bits N Bytes </h6>
                        </div>
                        <div class="client-say">
                            <div class="owl-carousel owl-theme" data-items="1" data-laptop="1" data-tablet="1" data-mobile="1" data-nav="false" data-dots="true" data-autoplay="true" data-speed="1800" data-autotime="5000">
                                <div class="item">
                                    <p><img src="images/taher.png" alt=""></p>
                                    <h5>Taher Said</h5>
                                    <p>Web Site Creator</p>
                                    <p>Student at Higher Institue Of Bizerte .
                                        <br> Class Information System Developpement 21
                                        <br>2nd Group</p>
                                </div>
                                <div class="item">
                                    <p><img src="images/houssem.png" alt=""></p>
                                    <h5>Houssem Troudi</h5>
                                    <p>Web Site Creator</p>
                                    <p>Student at Higher Institue Of Bizerte .
                                        <br> Class Information System Developpement 21
                                        <br>2nd Group</p>
                                </div>
                                <div class="item">
                                    <p><img src="images/monta.png" alt=""></p>
                                    <h5>Montassar Silini</h5>
                                    <p>Web Site Creator</p>
                                    <p>Student at Higher Institue Of Bizerte .
                                        <br> Class Information System Developpement 21
                                        <br>2nd Group</p>
                                </div>
                                <div class="item">
                                    <p><img src="images/takwa.png" alt=""></p>
                                    <h5>Takwa Mekni</h5>
                                    <p>Web Site Creator</p>
                                    <p>Student at Higher Institue Of Bizerte .
                                        <br> Class Information System Developpement 21
                                        <br>1st Group</p>
                                </div>
                                <div class="item">
                                    <p><img src="images/chrif.png" alt=""></p>
                                    <h5>Mohammed Chrif</h5>
                                    <p>Web Site Creator</p>
                                    <p>Student at Higher Institue Of Bizerte .
                                        <br> Class Information System Developpement 21
                                        <br>1st Group</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- End Client Say -->
                <!-- Start Feature list -->

                <!-- End Feature list -->
                <!-- Start Contact Part -->
                <section class="default-section contact-part home-icon" id="contact">
                    <div class="icon-default">
                        <a href="#"><img src="images/scroll-arrow.png" alt=""></a>
                    </div>
                    <div class="container">
                        <div class="title text-center">
                            <h2 class="text-coffee">Contact Us</h2>
                            <h6 class="heade-xs">We are a second-generation family business established in 1972</h6>
                        </div>
                        <div class="row">
                            <div class="col-md-4 col-sm-4 col-xs-12 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                                <div class="contact-blog-row">
                                    <div class="contact-icon">
                                        <img src="images/location-icon.png" alt="">
                                    </div>
                                    <p>Route Menzel Abderrahmen – Zarzouna 7021 Bizerte، 7021</p>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                                <div class="contact-blog-row">
                                    <div class="contact-icon">
                                        <img src="images/cell-icon.png" alt="">
                                    </div>
                                    <p><a href="tel:1234567890">23 349 082</a></p>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                                <div class="contact-blog-row">
                                    <div class="contact-icon">
                                        <img src="images/mail-icon.png" alt="">
                                    </div>
                                    <p><a href="mailto:support@despina.com">support@foody.com</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8 col-sm-8 col-xs-12 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                                <h5 class="text-coffee">Leave us a Message</h5>
                                <p>Aenean massa diam, viverra vitae luctus sed, gravida eget est. Etiam nec ipsum porttitor, consequat libero eu, dignissim eros. Nulla auctor lacinia enim id mollis.</p>
                                <form class="form" method="post" name="contact-form">
                                    <div class="row">
                                        <div class="alert-container"></div>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <label>First Name *</label>
                                            <input name="first_name" type="text" required>
                                        </div>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <label>Last Name *</label>
                                            <input name="last_name" type="text" required>
                                        </div>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <label>Email *</label>
                                            <input name="email" type="email" required>
                                        </div>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <label>Subject *</label>
                                            <input name="subject" type="text" required>
                                        </div>
                                        <div class="col-md-12 col-sm-12 col-xs-12">
                                            <label>Your Message *</label>
                                            <textarea name="message" required></textarea>
                                        </div>
                                        <div class="col-md-12 col-sm-12 col-xs-12">
                                            <input name="submit" value="SEND MESSAGE" class="btn-black pull-right send_message" type="submit">
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-12 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                                <h5 class="text-coffee">Opening Hours</h5>
                                <ul class="time-list">
                                    <li><span class="week-name">Monday</span> <span>12-6 PM</span></li>
                                    <li><span class="week-name">Tuesday</span> <span>12-6 PM</span></li>
                                    <li><span class="week-name">Wednesday</span> <span>12-6 PM</span></li>
                                    <li><span class="week-name">Thursday</span> <span>12-6 PM</span></li>
                                    <li><span class="week-name">Friday</span> <span>12-6 PM</span></li>
                                    <li><span class="week-name">Saturday</span> <span>12-6 PM</span></li>
                                    <li><span class="week-name">Sunday</span> <span>Closed</span></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- End Contact Part -->
            </div>
        </main>
        <!-- End Main -->
        <!-- Start Footer -->
        <footer>
            <div class="footer-part wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                <div class="icon-default icon-dark">
                    <img src="images/footer-logo.png" alt="">
                </div>
                <div class="container">
                    <div class="footer-inner">
                        <div class="footer-info">
                            <h3>Foody Restaurant</h3>
                            <p>Route Menzel Abderrahmen – Zarzouna 7021 Bizerte، 7021</p>
                            <p><a href="#">23 349 082</a></p>
                            <p><a href="#">support@foody.com</a></p>
                        </div>
                    </div>
                    <div class="copy-right">
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-xs-12 copyright-before">
                                <span>Copyright © 2019 xxx Theme. All rights reserved.</span>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12 copyright-after">
                                <div class="social-round">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                        <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                        <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                                        <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="icon-find">
                    <a href="#">
                        <img src="images/location.png" alt="">
                        <span>Find us on Map</span>
                    </a>
                </div>
                <div class="location-footer-map">
                    <div class="icon-find-location">
                        <a href="#">
                            <img src="images/location.png" alt="">
                            <span>Find us on Map</span>
                        </a>
                    </div>
                    <div class="footer-map-outer">
                        <div id="footer-map"></div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- End Footer -->
        <!-- Start Book Table -->
        <div class="modal fade booktable" id="login" tabindex="-1" role="dialog" aria-labelledby="login">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <div class="table-title">
                            <h2>Log In</h2>

                        </div>


                        <form class="login-form" method="post" name="login" action="<?= $_SERVER["PHP_SELF"]; ?>">
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <input type="text" name="email2" placeholder="<?php 
                                                                                    if(!isset($email_error2)) 
                                                                                        echo $emailPlaceHolder ;
                                                                                    else
                                                                                        echo $email_error2;
                                                                                ?>"
                                                                                style="<?php if(isset($email_error2)): ?>  
                                                                                    background-color: #f8d7da;
                                                                                    border-color: #f5c6cb;
                                                                                <?php endif; ?>"
                                                                                 class="input-fields form-control"
                                        value="<?php 
                                                    if(isset($_POST["email2"])&&(!isset($email_error2)))
                                                        echo $_POST["email2"];
                                                ?>" required>
                                </div>
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <input type="password" name="password" placeholder="<?php 
                                                                                    if(!isset($password_error2)) 
                                                                                        echo $password2PlaceHolder ;
                                                                                    else
                                                                                        echo $password_error2;
                                                                                ?>"
                                                                                style="<?php if(isset($password_error2)): ?>  
                                                                                    background-color: #f8d7da;
                                                                                    border-color: #f5c6cb;
                                                                                    box-shadow: inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px #f8d7da;<
                                                                                <?php endif; ?>"
                                                                                 class="input-fields form-control" required>
                                </div>
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="row">
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <label>
                                                <input type="checkbox" name="chkbox">Remember me</label>
                                        </div>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <a href="#" data-toggle="modal" data-target="#signUp" class="pull-right" class="close" data-dismiss="modal" aria-label="Close"><img src="images/login.png" alt="">Don't have an account?</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <input type="submit" name="logIn" value="LOGIN" class="button-default button-default-submit">
                                </div>


                            </div>

                        </form>
                    </div>


                </div>
            </div>
        </div>

        <div class="modal fade booktable" id="signUp" tabindex="-1" role="dialog" aria-labelledby="signUp">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <div class="table-title">
                            <h2>Sign Up</h2>

                        </div>


                        <form class="login-form" method="post" name="signUp" action="<?= $_SERVER["PHP_SELF"]; ?>">
                            <div class="row">
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" name="name" placeholder="<?php 
                                                                                    if(!isset($nameError)) 
                                                                                        echo $namePlaceHolder ;
                                                                                    else
                                                                                        echo $nameError;
                                                                                ?>"
                                                                                style="<?php if(isset($nameError)): ?>  
                                                                                    background-color: #f8d7da;
                                                                                    border-color: #f5c6cb;
                                                                                <?php endif; ?>"
                                                                                 class="input-fields form-control"
                                        value="<?php 
                                                    if(isset($_POST["name"])&&(!isset($nameError)))
                                                        echo $_POST["name"];
                                                ?>" required>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" name="phoneNumber" placeholder="Phone Number" placeholder="<?php 
                                                                                    if(!isset($phoneError)) 
                                                                                        echo $phonePlaceHolder ;
                                                                                    else
                                                                                        echo $phoneError;
                                                                                ?>"
                                                                                style="<?php if(isset($phoneError)): ?>  
                                                                                    background-color: #f8d7da;
                                                                                    border-color: #f5c6cb;
                                                                                <?php endif; ?>"
                                                                                 class="input-fields form-control"
                                        value="<?php 
                                                    if(isset($_POST["phoneNumber"])&&(!isset($phoneError)))
                                                        echo $_POST["phoneNumber"];
                                                ?>" required>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" name="email" placeholder="<?php 
                                                                                    if(!isset($emailError)) 
                                                                                        echo $emailPlaceHolder ;
                                                                                    else
                                                                                        echo $emailError;
                                                                                ?>"
                                                                                style="<?php if(isset($emailError)): ?>  
                                                                                    background-color: #f8d7da;
                                                                                    border-color: #f5c6cb;
                                                                                <?php endif; ?>"
                                                                                 class="input-fields form-control"
                                        value="<?php 
                                                    if(isset($_POST["email"])&&(!isset($emailError)))
                                                        echo $_POST["email"];
                                                ?>" required>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" name="adresse" placeholder="<?php 
                                                                                    if(!isset($addressError)) 
                                                                                        echo $addressPlaceHolder ;
                                                                                    else
                                                                                        echo $addressError;
                                                                                ?>"
                                                                                style="<?php if(isset($addressError)): ?>  
                                                                                    background-color: #f8d7da;
                                                                                    border-color: #f5c6cb;
                                                                                <?php endif; ?>"
                                                                                 class="input-fields form-control"
                                        value="<?php 
                                                    if(isset($_POST["adresse"])&&(!isset($addressError)))
                                                        echo $_POST["adresse"];
                                                ?>" required>
                                </div>

                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="password" name="password" placeholder="<?php 
                                                                                    if(!isset($passwordError)) 
                                                                                        echo $passwordPlaceHolder ;
                                                                                    else
                                                                                        echo $passwordError;
                                                                                ?>"
                                                                                style="<?php if(isset($passwordError)): ?>  
                                                                                    background-color: #f8d7da;
                                                                                    border-color: #f5c6cb;
                                                                                <?php endif; ?>"
                                                                                 class="input-fields form-control" required>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="password" name="passwordConf" placeholder="<?php 
                                                                                    if(!isset($passwordConfErr)) 
                                                                                        echo $passwordConfPlaceHolder ;
                                                                                    else
                                                                                        echo $passwordConfErr;
                                                                                ?>"
                                                                                style="<?php if(isset($passwordConfErr)): ?>  
                                                                                    background-color: #f8d7da;
                                                                                    border-color: #f5c6cb;
                                                                                <?php endif; ?>"
                                                                                 class="input-fields form-control" required>
                                </div>


                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <div class="row">
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <!--<label>
                                            <input type="checkbox" name="chkbox">Remember me</input>
                                            </label>-->
                                        </div>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <a href="#" data-toggle="modal" data-target="#login" class="pull-right" class="close" data-dismiss="modal" aria-label="Close"><img src="images/login.png" alt="">have an account?</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <input type="submit" name="signUp" value="LOGIN" class="button-default button-default-submit">
                                </div>
                            </div>
                        </form>
                    </div>


                </div>
            </div>
        </div>




    </div>
    </div>
    </div>






    </div>
    <!-- End Book Table -->
    </div>
    <!-- Back To Top Arrow -->
    <a href="#" class="top-arrow"></a>
    <script src="js/jquery.min.js"></script>
    <script src="plugin/bootstrap/bootstrap.min.js"></script>
    <script src="plugin/bootstrap/bootstrap-datepicker.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAf6My1Jfdi1Fmj-DUmX_CcNOZ6FLkQ4Os"></script>
    <script src="plugin/form-field/jquery.formstyler.min.js"></script>
    <script src="plugin/revolution-plugin/jquery.themepunch.plugins.min.js"></script>
    <script src="plugin/revolution-plugin/jquery.themepunch.revolution.min.js"></script>
    <script src="plugin/owl-carousel/owl.carousel.min.js"></script>
    <script src="plugin/slick-slider/slick.min.js"></script>
    <script src="plugin/isotop/isotop.js"></script>
    <script src="plugin/isotop/packery-mode.pkgd.min.js"></script>
    <script src="plugin/magnific/jquery.magnific-popup.min.js"></script>
    <script src="plugin/scroll-bar/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="plugin/animation/wow.min.js"></script>
    <script src="plugin/parallax/jquery.stellar.js"></script>
    <script src="js/app.js"></script>
    <script src="js/script.js"></script>
</body>


<!-- Mirrored from laboom.sk-web-solutions.com/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 05 Dec 2019 20:34:18 GMT -->

</html