<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from laboom.sk-web-solutions.com/blog_2col.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 05 Dec 2019 20:36:30 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog 2 Columns - Laboom</title>
    <link href="plugin/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="plugin/bootstrap/datepicker.css" rel="stylesheet">
    <link href="plugin/font-awesome/font-awesome.css" rel="stylesheet">
    <link href="plugin/form-field/jquery.formstyler.css" rel="stylesheet">
    <link href="plugin/revolution-plugin/extralayers.css" rel="stylesheet">
    <link href="plugin/revolution-plugin/settings.css" rel="stylesheet">
    <link href="plugin/owl-carousel/owl.carousel.css" rel="stylesheet">
    <link href="plugin/owl-carousel/owl.theme.default.css" rel="stylesheet">
    <link href="plugin/slick-slider/slick-theme.css" rel="stylesheet">
    <link href="plugin/magnific/magnific-popup.css" rel="stylesheet">
    <link href="plugin/scroll-bar/jquery.mCustomScrollbar.css" rel="stylesheet">
    <link href="plugin/animation/animate.min.css" rel="stylesheet">
    <link href="css/theme.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
    <link href="css/custom.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <!-- Page pre loader -->
    <div id="pre-loader">
        <div class="loader-holder">
            <div class="frame">
                <img src="images/Preloader.gif" alt="Foody" />
            </div>
        </div>
    </div>  
        <!-- Start Header -->
            <?php require "nav.php"; ?>
        <!-- End Header -->
       <!-- Start Main -->
       <main>
        <div class="main-part">
            <!-- Start Breadcrumb Part -->
            <section class="breadcrumb-part" data-stellar-offset-parent="true" data-stellar-background-ratio="0.5" style="background-image: url('images/breadbg1.jpg');">
                <div class="container">
                    <div class="breadcrumb-inner">
                        <h2>SHOP SINGLE</h2>
                        <a href="CustomerHome.php">Home</a>
                        <span>Shop</span>
                    </div>
                </div>
            </section>
            <!-- End Breadcrumb Part -->
            <section class="home-icon shop-single pad-bottom-remove">
                <div class="icon-default">
                    <img src="images/scroll-arrow.png" alt="">
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-12 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                            <div class="slider slider-for slick-shop">
                                <div>
                                    <img src="images/img64.png" alt="">
                                </div>
                                <div>
                                    <img src="images/img64.png" alt="">
                                </div>
                                <div>
                                    <img src="images/img64.png" alt="">
                                </div>
                                <div>
                                    <img src="images/img64.png" alt="">
                                </div>
                                <div>
                                    <img src="images/img64.png" alt="">
                                </div>
                                <div>
                                    <img src="images/img64.png" alt="">
                                </div>
                                <div>
                                    <img src="images/img64.png" alt="">
                                </div>
                                <div>
                                    <img src="images/img64.png" alt="">
                                </div>
                            </div>
                            <div class="slider slider-nav slick-shop-thumb">
                                <div><img src="images/img65.png" alt=""></div>
                                <div><img src="images/img65.png" alt=""></div>
                                <div><img src="images/img65.png" alt=""></div>
                                <div><img src="images/img65.png" alt=""></div>
                                <div><img src="images/img65.png" alt=""></div>
                                <div><img src="images/img65.png" alt=""></div>
                                <div><img src="images/img65.png" alt=""></div>
                                <div><img src="images/img65.png" alt=""></div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                            <h4 class="text-coffee"><?= $productInfo["name"]; ?></h4>
                            
                            <p><?= $productInfo["description"]; ?></p>
                            <h3 class="text-coffee"><?= $productInfo["price"]." TD"; ?></h3>
                            <section>
                                    <form action="<?= $_SERVER['PHP_SELF']."?pid=".$_GET["pid"]; ?>" method='POST'>
                                        <div class="price-textbox">

                                            <input type="text" name="quantity" placeholder="Quanitity" pattern="[0-9]">
                                            
                                        </div>
                                        <button href="" class="filter-btn btn-large" type="submit" name="cartAdd"><i class="fa fa-shopping-bag" aria-hidden="true"></i> Add to Cart</button>
                
                                    </form>
                                </section>

                            <div class="share-tag">
                                <div class="row">
                                    
                                    <div class="col-md-12 col-sm-12 col-xs-12">
                                        <div class="tag-wrap">
                                            <h5>TAGS</h5>
                                            <a href="#" class="tag-btn">Audio</a>
                                            <a href="#" class="tag-btn">Service</a>
                                            <a href="#" class="tag-btn">Cupcake</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Start Tab Part -->
            
            <section class="default-section comment-review-tab bg-grey v-pad-remove wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                    
                    <div class="build-title">
                            <h3></h3>
                    </div>
                <div class="title text-center">
                            
                    <h6 class="heade-xs"></h6>
                    <h6 class="heade-xs"></h6>
                </div>
            </section>
            <!-- End Tab Part -->
            <!-- Start Related Product -->
            <section class="related-product wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                <div class="container">
                    <div class="build-title">
                        <h3>Related Products</h3>
                    </div>
                    <div class="owl-carousel owl-theme" data-items="4" data-laptop="3" data-tablet="2" data-mobile="1" data-nav="false" data-dots="true" data-autoplay="true" data-speed="1800" data-autotime="5000">
                        <div class="item">
                            <div class="related-img">
                                <img src="images/img66.png" alt="">
                            </div>
                            <div class="related-info">
                                <h6><a href="#">Blanched Garlic</a></h6>
                                <h6><a href="#"><strong>$ 15.00</strong></a></h6>
                            </div>
                        </div>
                        <div class="item">
                            <div class="related-img">
                                <img src="images/img67.png" alt="">
                            </div>
                            <div class="related-info">
                                <h6><a href="#">Blanched Garlic</a></h6>
                                <h6><a href="#"><strong>$ 15.00</strong></a></h6>
                            </div>
                        </div>
                        <div class="item">
                            <div class="related-img">
                                <img src="images/img68.png" alt="">
                            </div>
                            <div class="related-info">
                                <h6><a href="#">Blanched Garlic</a></h6>
                                <h6><a href="#"><strong>$ 15.00</strong></a></h6>
                            </div>
                        </div>
                        <div class="item">
                            <div class="related-img">
                                <img src="images/img69.png" alt="">
                            </div>
                            <div class="related-info">
                                <h6><a href="#">Blanched Garlic</a></h6>
                                <h6><a href="#"><strong>$ 15.00</strong></a></h6>
                            </div>
                        </div>
                        <div class="item">
                            <div class="related-img">
                                <img src="images/img66.png" alt="">
                            </div>
                            <div class="related-info">
                                <h6><a href="#">Blanched Garlic</a></h6>
                                <h6><a href="#"><strong>$ 15.00</strong></a></h6>
                            </div>
                        </div>
                        <div class="item">
                            <div class="related-img">
                                <img src="images/img67.png" alt="">
                            </div>
                            <div class="related-info">
                                <h6><a href="#">Blanched Garlic</a></h6>
                                <h6><a href="#"><strong>$ 15.00</strong></a></h6>
                            </div>
                        </div>
                        <div class="item">
                            <div class="related-img">
                                <img src="images/img68.png" alt="">
                            </div>
                            <div class="related-info">
                                <h6><a href="#">Blanched Garlic</a></h6>
                                <h6><a href="#"><strong>$ 15.00</strong></a></h6>
                            </div>
                        </div>
                        <div class="item">
                            <div class="related-img">
                                <img src="images/img69.png" alt="">
                            </div>
                            <div class="related-info">
                                <h6><a href="#">Blanched Garlic</a></h6>
                                <h6><a href="#"><strong>$ 15.00</strong></a></h6>
                            </div>
                        </div>
                        <div class="item">
                            <div class="related-img">
                                <img src="images/img66.png" alt="">
                            </div>
                            <div class="related-info">
                                <h6><a href="#">Blanched Garlic</a></h6>
                                <h6><a href="#"><strong>$ 15.00</strong></a></h6>
                            </div>
                        </div>
                        <div class="item">
                            <div class="related-img">
                                <img src="images/img67.png" alt="">
                            </div>
                            <div class="related-info">
                                <h6><a href="#">Blanched Garlic</a></h6>
                                <h6><a href="#"><strong>$ 15.00</strong></a></h6>
                            </div>
                        </div>
                        <div class="item">
                            <div class="related-img">
                                <img src="images/img68.png" alt="">
                            </div>
                            <div class="related-info">
                                <h6><a href="#">Blanched Garlic</a></h6>
                                <h6><a href="#"><strong>$ 15.00</strong></a></h6>
                            </div>
                        </div>
                        <div class="item">
                            <div class="related-img">
                                <img src="images/img69.png" alt="">
                            </div>
                            <div class="related-info">
                                <h6><a href="#">Blanched Garlic</a></h6>
                                <h6><a href="#"><strong>$ 15.00</strong></a></h6>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- End Related Product -->
        </div>
    </main>
    <!-- End Main -->
       <!-- Start Footer -->
       <footer>
        <div class="footer-part wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
            <div class="icon-default icon-dark">
                <img src="images/footer-logo.png" alt="">
            </div>
            <div class="container">
                <div class="footer-inner">
                    <div class="footer-info">
                        <h3>Foody Restaurant</h3>
                        <p>Route Menzel Abderrahmen – Zarzouna 7021 Bizerte، 7021</p>
                        <p><a href="#">23 349 082</a></p>
                        <p><a href="#">support@foody.com</a></p>
                    </div>
                </div>
                <div class="copy-right">
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-12 copyright-before">
                            <span>Copyright © 2019 xxx Theme. All rights reserved.</span>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12 copyright-after">
                            <div class="social-round">
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google" aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="icon-find">
                <a href="#">
                    <img src="images/location.png" alt="">
                    <span>Find us on Map</span>
                </a>
            </div>
            <div class="location-footer-map">
                <div class="icon-find-location">
                    <a href="#">
                        <img src="images/location.png" alt="">
                        <span>Find us on Map</span>
                    </a>
                </div>
                <div class="footer-map-outer">
                    <div id="footer-map"></div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer -->
        <!-- Start Book Table -->
        <!-- End Book Table -->
    </div>
    <!-- Back To Top Arrow -->
    <a href="#" class="top-arrow"></a>
    <script src="js/jquery.min.js"></script>
    <script src="plugin/bootstrap/bootstrap.min.js"></script>
    <script src="plugin/bootstrap/bootstrap-datepicker.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAf6My1Jfdi1Fmj-DUmX_CcNOZ6FLkQ4Os"></script>
    <script src="plugin/form-field/jquery.formstyler.min.js"></script>
    <script src="plugin/revolution-plugin/jquery.themepunch.plugins.min.js"></script>
    <script src="plugin/revolution-plugin/jquery.themepunch.revolution.min.js"></script>
    <script src="plugin/owl-carousel/owl.carousel.min.js"></script>
    <script src="plugin/slick-slider/slick.min.js"></script>
    <script src="plugin/isotop/isotop.js"></script>
    <script src="plugin/isotop/packery-mode.pkgd.min.js"></script>
    <script src="plugin/magnific/jquery.magnific-popup.min.js"></script>
    <script src="plugin/scroll-bar/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="plugin/animation/wow.min.js"></script>
    <script src="plugin/parallax/jquery.stellar.js"></script>
    <script src="js/app.js"></script>
    <script src="js/script.js"></script>
</body>

<!-- Mirrored from laboom.sk-web-solutions.com/blog_2col.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 05 Dec 2019 20:36:33 GMT -->
</html>